apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpndwpNekEzTVROYUZ3MDBNekF4TWpnd016QTNNVE5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEZTFkdFpKbHBnKzB1S2oxY0ZCaXpycERlR0FXTUJnWHNJVU1ranlCd0JxQWFZVE54WQpRSUhyQ0tKSW1nT1VmN0FOak96a1JuSFowSEo2c25aY1IxWVRQQ201WXJwY1FaL09ZL0hZSjBVWWNuamN3ck5qCmdtTWZLM3k4YituaXIwTjVkdDRGSjdzOVFIcXhld28zeFQrU00wWWxrK3lrVUVzcFdlZWh6T0RUdUovbUMrT0gKZ0g5TEdFcEpWdkx2cnVXSllYUG1XWC93MS91Ym94MnFjc0dJNVEvdkZjbHFGcUVDV3FKUWVUeFNxYzRYUVFMSwpDNDlTNm42MkJZWFRuTk8wZVoyZG5RWFV5dGd4Z1k1MlFkSzZGMWpFN2hQVzV6dTQrNFpGS3cwUGRERzdXT2xzClRpVjE4cVMyQzhuZUY3TmRaT1dZL1NXRFBWWFhOaDV6c0hVOUFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJSYllKNkhwL09pQ2NyZTAvVwowWXkxYm96ZVF6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFJdTZpM3BabVNyRFdrZlBDM0IwQzNGa3dtNmZzClU0RVovMituaUJCblFtQ2J5aEpnRmFDQzVvRTJ5QTV5OStTR1V0Z0VSb1JQTUoybVAwSXNwME8rTE4yUHRoYmgKR2JwdkVDTGxwTnVvUlhGRWN4Nm9sNHJvTXhCRUlHTEpzeG1sL1BDUnUyZVFESk9ZbDBSZzBSNjdMeWlCeEF6cgpqVmU1N0p1SHUyR3BmdGU3UzcxTWxQb0Rua2NaMTgzMm0xV1c2T2RuVVJTa0Z1VGRzVGFraWtNeTNkZHM1NllsCk56Z2IrejkxSGhXZVJGWFlrQUd0K2ltcDYwT0puYnBhTUtXcWhwVXlka1JieHZpMVo5MXBEeDJMUG1IdjlVOGkKZnA2SW9GSldtSnRMVHdCNGtGQ1VqN3FXN0V0eWhKQXhiaHFsOEtvZ3VBL0IyaFN6bk9CemR5T3lXUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://4a98dc18-ddac-48c6-8d72-a50dd6927e7b.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_64daee98e6c36d39f7fe974a191c964d0962743be672b4b1bd0080fa3118c005
